### ISSUE TITLE
removeChild error when trying to unmount Icon component

### ISSUE THREAD

**Issue by elitenoire** [dimitrisraptis96/react-eva-icons#2]
I get this error when trying to remove the Icon component from the DOM:
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (http://localhost:3000/static/js/1.chunk.js:87249:22)
...
```
I'm using the loading icon and want to show it only when I'm submitting a form.
I used it like this:
```
<Button
	className="medium w-100"
	type="submit"
	disabled={isSubmitting}
>
	{isSubmitting && (
	<Icon
		name="loader-outline"
		size="medium"
		animation={{ type: 'pulse', infinite: true, hover: false }}
	/>
	)}
	{!isSubmitting ? (signup ? 'Create Account' : 'Sign In') : ''}
</Button>
```

**Comment by elitenoire** [comment]
This stackoverflow [question](https://stackoverflow.com/questions/48358529/failed-to-execute-removechild-on-node-with-fontawesome-in-react) has a possible solution.

**Comment by dimitrisraptis96** [comment]
Hey, @elitenoire 👋 
Could you provide my a Github repo/gist or a [CodeSandBox](https://codesandbox.io/) project in order to reproduce your issue and help you?

**Comment by dimitrisraptis96** [comment]
Ping me to re-open it in case you still have the same problem
