### ISSUE TITLE
Unexpected token . when importing Icon

### ISSUE THREAD

**Issue by KanariTech** [dimitrisraptis96/react-eva-icons#3]
Whenever I `import Icon from 'react-eva-icons', I'm getting a 

`Unexpected token .` in the console log. 

`
at new Script
at createScript
at Object.runInThisContext
at Module._compile
at Object.Module._extensions..js
at Module.load
at tryModuleLoad
at Function.Module._load
at Module.require
at require
`
I'm importing it in my https://github.com/electron-react-boilerplate/electron-react-boilerplate project. 

Thanks.

**Comment by dimitrisraptis96** [comment]
Just pushed a new version 0.0.8 that handles your problem @KanariTech . It seemed that requiring CSS files in Electron has some issues.  

Enjoy coding and ping me if you face any other issue ✌️
